### ISSUE TITLE
Get the source path in your demo

### ISSUE THREAD

**Issue by Fliflomo123** [andyvr/picEdit#11]
Hey (:
I am not able to get the Source Path for the FTP UPload from your demo project?
Would be nice if you can answer (:

**Comment by andyvr** [comment]
The picEdit does not provide any means to handle the upload on the server-side. It's purely front-end project. It will take care of sending your data to the back-end, but that's it. You'll have to decide on what to do with the uploaded data on the back-end.

**Comment by Fliflomo123** [comment]
Hey (: if i want to upload an edited photo to a FTP Server, how do i have
to change httprequest or should i do it in another way
Am 27.01.2015 16:03 schrieb "Andy V." <notifications@github.com>:

**Comment by andyvr** [comment]
You don't change anything. You just access $_FILES array (php) or any other standard means of getting the uploaded file. picEdit uses standard upload means.
