### ISSUE TITLE
Mobile responsive?

### ISSUE THREAD

**Issue by jaysudo** [andyvr/picEdit#14]
Hi. I really like this plugin. Is there any way we can make it mobile responsive? I'm trying to dig into the code to find it but the dimensions of the canvas seem to be hardcoded. Can I get help with this?

**Comment by jaysudo** [comment]
found it. nvm ;-)

**Comment by brandecho** [comment]
You never added the solution to hardcode the dimensions of the canvas to make it responsive for mobile.
