### ISSUE TITLE
Passing Parameters

### ISSUE THREAD

**Issue by Belaird** [andyvr/picEdit#3]
How do I pass the variables to the out.php file?

**Comment by allox** [comment]
what took me a while to figure out:
the POST variable name for the image is 'file'.  $_POST['file']
(This seems to be somewhere hidden in the js.)
It would be nice if this what configurable, since my forms inputfields usually have different names.

**Comment by andyvr** [comment]
The variable name can be specified in the html markup, like so: <input type="file" name="imagefile" id="thebox">
Name property is the name for the variable.
