### ISSUE TITLE
"no video source detected..."

### ISSUE THREAD

**Issue by zynis** [andyvr/picEdit#50]
I tried this on Max OSX Chrome and on Android 4.4 Chrome, and both got the same result.

I'd really love to try this out for a project but is this the default case when trying to use the camera?

**Comment by jaskaran-kalra** [comment]
https://github.com/jhuckaby/webcamjs

Open the above url and read Important Note for Chrome 47+ u will get the answer there..

**Comment by andyvr** [comment]
I've updated the demo to use https instead of http.
Thank you guys for spotting this out. Looks like from now on only pages served from https can access camera!
