### ISSUE TITLE
Not issue but a question

### ISSUE THREAD

**Issue by dawondyifraw** [andyvr/picEdit#55]
![abcc](https://cloud.githubusercontent.com/assets/9797257/13137215/82a10ac0-d630-11e5-843d-46f4a8ef8f71.png)
![Uploading abcc.png…]()

Hey , Guys

I love this plugin , it is great tool. I m implementing a new layout accordingly  based on this plugin but , i have 5 image box which  that user need to select and upload at least to some temp folder when upload button / submit is clicked , later i need that image to be previewd when upload is done and dialog is finsihed , in same manner edit and delete should work also . 

am confised with your server side code .  (outphp)

Thanks ? 
![Uploading abcc.png…]()

**Comment by andyvr** [comment]
out.php displays the uploaded image(s) on the server side. This is very simple code example with bare code to display the uploaded, no error checks or any extra logic.
The code for saving images would be very similar, just replace the following piece of code:

```
$imgData = base64_encode(file_get_contents($file['tmp_name']));
$src = 'data: '.$file['type'].';base64,'.$imgData;
echo '<img src="'.$src.'"><br>';
```

with this one-liner

```
move_uploaded_file($file['tmp_name'], "./".$file['name']);
```
