### ISSUE TITLE
Firefox not display image in canvas

### ISSUE THREAD

**Issue by Kaki88** [andyvr/picEdit#8]
Hello, very usefull, great job (sorry for my english)

So, your live demo run on firefox (last version) but not in my server or local test....nothing image display (clipboard or upload manually...same way), canvas box stay empty , any idea ?

But work like a charm on google chrome....

Thanks

**Comment by allox** [comment]
Same. 
I'm using FF and paste or showing the image doesn't work anymore.
Previous version was fine 
(ps. add a version number to picedit.js )

**Comment by andyvr** [comment]
Thank you for spotting this issue.
